### ISSUE TITLE
[Does Not Work V4.5.3] Unable to get response from google cloud translation : replaceString.replace is not a function

### ISSUE THREAD

**Issue by z0lo13** [manishkatyan/strapi-google-translator#12]
Cannot Make it work. The following error when clicking translate:

![image](https://user-images.githubusercontent.com/23143958/205674690-7e092caf-effd-4566-9dbb-8e164610c247.png)

```
TypeError: replaceString.replace is not a function
	at Object.preProcessGlossary (~/node_modules/strapi-google-translator/server/services/translationServiceGoogle.js:206:39)
	at Object.translateText (~/node_modules/strapi-google-translator/server/services/translationServiceGoogle.js:171:31)
	at Object.getTranslationStrategy (~/node_modules/strapi-google-translator/server/services/translationServiceGoogle.js:140:25)
	at Object.doTranslation (~/node_modules/strapi-google-translator/server/services/translationServiceGoogle.js:46:35)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:95:5)
	at async Object.doTranslation (~/node_modules/strapi-google-translator/server/services/translateService.js:131:28)
	at async Object.translate (~/node_modules/strapi-google-translator/server/services/translateService.js:42:34)
	at async Object.translate (~/node_modules/strapi-google-translator/server/controllers/translateController.js:19:24)
	at async returnBodyMiddleware (~/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
	at async policiesMiddleware (~/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
	at async ~/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
	at async ~/node_modules/@strapi/strapi/lib/middlewares/logger.js:25:5
	at async ~/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
	at async cors (~/node_modules/@koa/cors/index.js:107:16)
	at async ~/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
ApplicationError: Unable to get response from google cloud translation : replaceString.replace is not a function
	at Object.doTranslation (~/node_modules/strapi-google-translator/server/services/translationServiceGoogle.js:83:13)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:95:5)
	at async Object.doTranslation (~/node_modules/strapi-google-translator/server/services/translateService.js:131:28)
	at async Object.translate (~/node_modules/strapi-google-translator/server/services/translateService.js:42:34)
	at async Object.translate (~/node_modules/strapi-google-translator/server/controllers/translateController.js:19:24)
	at async returnBodyMiddleware (~/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
	at async policiesMiddleware (~/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
	at async ~/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
	at async ~/node_modules/@strapi/strapi/lib/middlewares/logger.js:25:5
	at async ~/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
	at async cors (~/node_modules/@koa/cors/index.js:107:16)
	at async ~/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
	at async session (~/node_modules/koa-session/index.js:41:7)
	at async ~/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5 {
  details: {}
}
ApplicationError: Unable to get response from google cloud translation : replaceString.replace is not a function
	at Object.doTranslation (~/node_modules/strapi-google-translator/server/services/translationServiceGoogle.js:83:13)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:95:5)
	at async Object.doTranslation (~/node_modules/strapi-google-translator/server/services/translateService.js:131:28)
	at async Object.translate (~/node_modules/strapi-google-translator/server/services/translateService.js:42:34)
	at async Object.translate (~/node_modules/strapi-google-translator/server/controllers/translateController.js:19:24)
	at async returnBodyMiddleware (~/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
	at async policiesMiddleware (~/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
	at async ~/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
	at async ~/node_modules/@strapi/strapi/lib/middlewares/logger.js:25:5
	at async ~/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
	at async cors (~/node_modules/@koa/cors/index.js:107:16)
	at async ~/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
	at async session (~/node_modules/koa-session/index.js:41:7)
	at async ~/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5 {
  details: {}
}
```
"dependencies": {
    "@bn-digital/strapi-plugin-field-uuid": "^1.1.7",
    "@notum-cz/strapi-plugin-content-versioning": "^0.4.4",
    "@strapi/plugin-graphql": "^4.5.3",
    "@strapi/plugin-i18n": "4.5.3",
    "@strapi/plugin-seo": "^1.7.7",
    "@strapi/plugin-users-permissions": "4.5.3",
    "@strapi/provider-upload-cloudinary": "^4.5.3",
    "@strapi/strapi": "4.5.3",
    "moment": "^2.29.4",
    "mysql": "2.18.1",
    "sharp": "^0.31.2",
    "strapi-google-translator": "^1.0.7",
    "strapi-plugin-fast-content": "^1.0.0",
    "strapi-plugin-fuzzy-search": "^1.10.2",
    "strapi-plugin-import-export-entries": "^1.18.0",
    "strapi-plugin-menus": "^1.1.0",
    "strapi-plugin-placeholder": "^4.3.6",
    "strapi-plugin-sitemap": "boazpoolman/strapi-plugin-sitemap#beta"
  },
```

**Comment by nishekh-e-r** [comment]
@z0lo13 Hi,
I have tested the plugin with the latest strapi v4.5.3, and it's working fine, take a look at the attached image.
Also can you please provide more information on which test case scenarios the above error occurs?

![google-translate1](https://user-images.githubusercontent.com/87962465/206419887-88b99f08-aaef-4ffc-bce1-54b5af4e9d8d.png)

![google-translator2](https://user-images.githubusercontent.com/87962465/206419884-b2c34d7b-7d2e-417d-ae6e-ee8b4d40e494.png)

![google-translator3](https://user-images.githubusercontent.com/87962465/206419882-79b19981-d0a5-43d3-ae3d-983d8ec5b38b.png)

![google-translator4](https://user-images.githubusercontent.com/87962465/206419876-ba4f5799-6967-4035-9dc6-4357ad4415f4.png)
