### ISSUE TITLE
npm install on strapi 4.4.3: ERESOLVE unable to resolve dependency tree on

### ISSUE THREAD

**Issue by dmarkbreiter** [manishkatyan/strapi-google-translator#15]
Issues installing the plugin on Strapi 4.4.3. Below are my error logs after running `npm install strapi-google-translator`:
```
0 verbose cli [
0 verbose cli   '/Users/user/.nvm/versions/node/v16.14.2/bin/node',
0 verbose cli   '/Users/user/.nvm/versions/node/v16.14.2/bin/npm',
0 verbose cli   'install',
0 verbose cli   'strapi-google-translator'
0 verbose cli ]
1 info using npm@8.5.0
2 info using node@v16.14.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/user/Code/cnc/strapi-backend/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/user/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/user/.nvm/versions/node/v16.14.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 timing npm:load:configload Completed in 8ms
20 timing npm:load:setTitle Completed in 16ms
21 timing config:load:flatten Completed in 3ms
22 timing npm:load:display Completed in 5ms
23 verbose logfile /Users/user/.npm/_logs/2023-01-21T00_04_15_646Z-debug-0.log
24 timing npm:load:logFile Completed in 5ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 35ms
28 timing arborist:ctor Completed in 0ms
29 silly logfile start cleaning logs, removing 1 files
30 timing idealTree:init Completed in 677ms
31 timing idealTree:userRequests Completed in 3ms
32 silly idealTree buildDeps
33 silly fetch manifest strapi-google-translator@*
34 timing arborist:ctor Completed in 0ms
35 http fetch GET 200 https://registry.npmjs.org/strapi-google-translator 593ms (cache hit)
36 silly fetch manifest @strapi/strapi@4.4.3
37 http fetch GET 200 https://registry.npmjs.org/@strapi%2fstrapi 7ms (cache hit)
38 silly fetch manifest @strapi/strapi@^4.4.5
39 timing idealTree Completed in 1293ms
40 timing command:install Completed in 1306ms
41 verbose stack Error: unable to resolve dependency tree
41 verbose stack     at Arborist.[failPeerConflict] (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1399:25)
41 verbose stack     at Arborist.[loadPeerSet] (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1365:34)
41 verbose stack     at async Arborist.[buildDepStep] (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:951:11)
41 verbose stack     at async Arborist.buildIdealTree (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:215:7)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:152:5)
41 verbose stack     at async Install.exec (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/npm/lib/commands/install.js:157:5)
41 verbose stack     at async module.exports (/Users/user/.nvm/versions/node/v16.14.2/lib/node_modules/npm/lib/cli.js:66:5)
42 verbose cwd /Users/user/Code/cnc/strapi-backend
43 verbose Darwin 21.2.0
44 verbose argv "/Users/user/.nvm/versions/node/v16.14.2/bin/node"
45 verbose node v16.14.2
46 verbose npm  v8.5.0
47 error code ERESOLVE
48 error ERESOLVE unable to resolve dependency tree
49 error
50 error While resolving: [1mstrapi-test[22m@[1m0.1.0[22m
50 error Found: [1m@strapi/strapi[22m@[1m4.4.3[22m[2m[22m
50 error [2mnode_modules/@strapi/strapi[22m
50 error   [1m@strapi/strapi[22m@"[1m4.4.3[22m" from the root project
50 error
50 error Could not resolve dependency:
50 error [35mpeer[39m [1m@strapi/strapi[22m@"[1m^4.4.5[22m" from [1mstrapi-google-translator[22m@[1m1.0.7[22m[2m[22m
50 error [2mnode_modules/strapi-google-translator[22m
50 error   [1mstrapi-google-translator[22m@"[1m*[22m" from the root project
50 error
50 error Fix the upstream dependency conflict, or retry
50 error this command with --force, or --legacy-peer-deps
50 error to accept an incorrect (and potentially broken) dependency resolution.
50 error
50 error See /Users/user/.npm/eresolve-report.txt for a full report.
51 verbose exit 1
52 timing npm Completed in 1798ms
53 verbose unfinished npm timer reify 1674259456138
54 verbose unfinished npm timer reify:loadTrees 1674259456148
55 verbose unfinished npm timer idealTree:buildDeps 1674259456829
56 verbose unfinished npm timer idealTree:#root 1674259456829
```

**Comment by nishekh-e-r** [comment]
@dmarkbreiter, we are working on this issue, and will update you once it's fixed.

**Comment by dmarkbreiter** [comment]
> @dmarkbreiter, we are working on this issue, and will update you once it's fixed.

Would upgrading Strapi to v4.5 fix the issue?

**Comment by nishekh-e-r** [comment]
@dmarkbreiter yes it will fix the issue.
Also, I will update the dependency array so the package will support strapi 4.x.x
